export * as productTag from './components/productTag'
export * as productCategory from './components/productCategory'
export * as productComparisonCategory from './components/productComparisonCategory'
export * as productComparisonSubCategory from './components/productComparisonSubCategory'
export * as productManager from './components/productManager'
