export const actionTypes = {
  // get setting type
  GET_BACKEND_SETTING_START: 'GET_BACKEND_SETTING_START',
  GET_BACKEND_SETTING_SUCCESS: 'GET_BACKEND_SETTING_SUCCESS',
  GET_BACKEND_SETTING_FINISH: 'GET_BACKEND_SETTING_FINISH',
}
